apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: orders-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: orders-trigger
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: orders-listener
spec:
  to:
    kind: Service
    name: el-orders-listener
  port:
    targetPort: http-listener
