apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: orders-trigger
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: cel
      params:
        - name: filter
          value: body.ref == 'refs/heads/master'
  bindings:
    - ref: orders-binding
  template:
    ref: orders-template
