apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: orders-template
spec:
  params:
    - name: git-repo-url
      description: The git repository url
    - name: git-revision
      description: The git revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: orders-pipeline-run-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: orders-pipeline
        params:
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_REF
            value: $(tt.params.git-revision)
          - name: BASE_URL
            value: "http://orders-divikapoor-dev.apps.rm2.thpm.p1.openshiftapps.com"
        workspaces:
          - name: pipeline-workspace
            persistentVolumeClaim:
              claimName: pipeline-pvc
